insert into users
  (id, email, username, role, projects, avatar, fullname, is_active)
values
  ('339cbaac-2731-47a6-b0bb-e68be14addb9', 'magicpan@example.gg', 'magicpan', 'USER', '{"Galileo","Website redesign","Mobile app"}', 'https://ui-avatars.com/api/?name=PR&background=4e73df&color=fff', 'Patrik Radkow', 'true'),
  ('a65cbfa0-6802-480d-8bb4-26c549139b03', 'niceadmin@mail.com', 'admin', 'ADMIN', '{"Springfield media","Sky High Architecture","Data analysis","Marketing campaign"}', 'https://ui-avatars.com/api/?name=MH&background=1cc88a&color=fff', 'Martin Hoff', 'true'),
  ('4e552ab3-a423-4ac1-a021-67cace904667', 'ebrown@gmail.com', 'ebrown', 'USER', '{"Jenkins","Galileo","Cloud migration","AI integration","UX research","Mobile app","Frontend revamp","Backend optimization"}', 'https://ui-avatars.com/api/?name=LM&background=36b9cc&color=fff', 'Liz Macintosh', 'true'),
  ('fb440953-7f86-4c2b-aa30-e7e2fd7ad2ca', 'mrm@gmail.com', 'mrm', 'OWNER', '{"Mood board","Jenkins","Project management","Team building","Strategic planning"}', 'https://ui-avatars.com/api/?name=M2&background=f6c23e&color=fff', 'M2', 'true'),
  ('b5956956-8b00-4983-881c-dd83837ee62b', 'kevin@gmail.com', 'kevin13', 'USER', '{"Vuestic","Mood board","E-commerce platform","Customer support","Data visualization","Mobile app"}', 'https://ui-avatars.com/api/?name=KS&background=e74a3b&color=fff', 'Kevin Smith', 'true'),
  ('3af55b61-8e02-4381-afa7-8feba83a0bfe', 'martin@gmail.com', 'martin3', 'USER', '{"Toolset landing","Design team project","Branding refresh","UI kit development"}', 'https://ui-avatars.com/api/?name=MH&background=858796&color=fff', 'Martin Hoff', 'true'),
  ('5f4b4c3a-5fe3-4525-a86e-e11c5a2e6a81', 'john@mail.com', 'john', 'USER', '{"Jenkins","Springfield media","Code refactoring","Performance optimization","Security audit","Documentation"}', 'https://ui-avatars.com/api/?name=JD&background=5a5c69&color=fff', 'John Doe', 'true'),
  ('7e50a660-8439-480f-bf76-753e8848d964', 'maksim@epic.com', 'maksim', 'ADMIN', '{"Mood board","Website redesign","API development","Database migration","DevOps implementation","Testing automation"}', 'https://ui-avatars.com/api/?name=MN&background=e74a3b&color=fff', 'Maksim Nedo', 'true'),
  ('fb8e615e-5b55-4444-975e-aa8e8ab25455', 'sconnor@skynet.com', 'sconnor', 'USER', '{"AI Safety","Robotics","Time Travel Logistics"}', 'https://ui-avatars.com/api/?name=SC&background=20c997&color=fff', 'Sarah Connor', 'true'),
  ('1d3524b4-ed8d-4b91-b7f8-9f10abdf7fa6', 'tony@starkindustries.com', 'ironman', 'ADMIN', '{"Arc Reactor","Suit Enhancements","Clean Energy"}', 'null', 'Tony Stark', 'true'),
  ('aa6730e8-ac37-41e2-88d8-a89a70152513', 'bbanner@avengers.org', 'hulk', 'USER', '{"Gamma Radiation Studies","Anger Management App","Super Soldier Serum"}', 'https://ui-avatars.com/api/?name=BB&background=6f42c1&color=fff', 'Bruce Banner', 'true'),
  ('b762dba8-f4d1-4d27-a00b-aa8869c7feb7', 'spidey@dailybugle.com', 'webslinger', 'USER', '{"Web Fluid Formula","City Surveillance System","Acrobatics Training Program"}', 'https://ui-avatars.com/api/?name=PP&background=e83e8c&color=fff', 'Peter Parker', 'true'),
  ('974d606e-81a9-4346-b117-8e8443c16c59', 'ww@themyscira.gov', 'wonderwoman', 'ADMIN', '{"Lasso of Truth","Invisible Jet Maintenance","Amazonian Archive Digitization"}', 'https://ui-avatars.com/api/?name=DP&background=fd7e14&color=fff', 'Diana Prince', 'true'),
  ('df2f0afe-4c9e-4a22-861a-3250c07afde9', 'superman@dailyplanet.com', 'ckent', 'USER', '{"Kryptonian Language Preservation","Solar Energy Absorption","Metropolis Reconstruction"}', 'https://ui-avatars.com/api/?name=CK&background=6610f2&color=fff', 'Clark Kent', 'true'),
  ('12a983e7-20af-4a5b-820c-4122064dd136', 'blackwidow@shield.gov', 'nromanoff', 'ADMIN', '{"Spy Network Management","Infiltration Techniques","Combat Training Simulator"}', 'https://ui-avatars.com/api/?name=NR&background=dc3545&color=fff', 'Natasha Romanoff', 'true'),
  ('f779e25b-e79d-430b-bd4c-887cdc21203a', 'cap@avengers.org', 'capamerica', 'USER', '{"Shield Aerodynamics","1940s Cultural Integration","Team Leadership Workshop"}', 'https://ui-avatars.com/api/?name=SR&background=007bff&color=fff', 'Steve Rogers', 'true')